Fix NPE, Fix transition from _v to _vt
bxservice/idempiere-rest pull request #120
Opened 2022-09-02 06:19 UTC by igorpojzl

Ticket https://github.com/bxservice/idempiere-rest/issues/117
RestUtils:139 -> fix NPE when _vt is not created in Application Dictionary
RestUtils:116 -> Fix Transition from _v to _vt, language was not applied

2022-09-02 10:05 UTC, CarlosRuiz-globalqss commented on com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/json/RestUtils.java
> +		if (table != null && table.isView() && table.getTableName().toLowerCase().endsWith("_vt")) {
what's the goal of this change?
if tableName is null then the variable table is null and the condition is not reached

2022-09-02 10:05 UTC, CarlosRuiz-globalqss commented on com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/json/RestUtils.java
> +				MTable t_table = MTable.get(Env.getCtx(), tableName+ "t");
what's the goal of this change?
the variable hasVT already confirmed that the table _vt exists, so it's not necessary to check again for its existence

2022-09-02 10:57 UTC, CarlosRuiz-globalqss commented
Nevermind about my comments, Diego analyzed it better and explained to me

2022-09-02 11:04 UTC, CarlosRuiz-globalqss requested changes
Hi @igorpojzl - can you please apply the following patch on top of this PR and test if it works the same?

[pr120_PR.txt](https://github.com/bxservice/idempiere-rest/files/9477336/pr120_PR.txt)

Regards,

Carlos Ruiz

2022-09-05 07:57 UTC, igorpojzl commented
I have additional fix which is caused by this PR.

2022-09-05 08:02 UTC, igorpojzl commented
Added Fix Duplicating Parameters of AD_Language caused by mutation of cached convertedStatement

2022-09-05 10:59 UTC, CarlosRuiz-globalqss commented
Thanks @igorpojzl - how is the test case for the last change on duplicated parameters?

2022-09-05 11:07 UTC, igorpojzl commented
Make min. 2 same GET POs call on any _vt table
or _v table which has _vt table.
Each call will update cached Parameters List, but where condition is not updated.

2022-10-18 12:48 UTC, CarlosRuiz-globalqss commented
@igorpojzl - I did some additional tests and the following patch is necessary:
[pr120_PR2.txt](https://github.com/bxservice/idempiere-rest/files/9810493/pr120_PR2.txt)

It fixes a bug introduced with previous commit for this same issue (base language doesn't require using _vt)

2022-10-26 18:40 UTC, norbertbede commented
@igorpojzl  pls apply this patch. and test the change. n

2022-11-03 12:11 UTC, merged